services:
  - type: web
    name: lstm-stock-predictor
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
